#!/usr/bin/with-contenv bash

PUID=${PUID:-313}
PGID=${PGID:-313}

groupmod -o -g "$PGID" unbound
usermod -o -u "$PUID" unbound

echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u unbound)
User gid:    $(id -g unbound)
-------------------------------------
"
chown -R unbound:unbound /etc/unbound
